<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI SSO Bridge plugin - SSO portal client
 *
 * Talks to the SSO portal ("bridge" API) using the access token stored in
 * the configuration:
 *
 *   GET {portal}bridge/cid?token=...            -> new correlation id
 *   GET {portal}bridge/check?token=...&correlationId=...
 *                                               -> validated identity (email/username)
 *   GET {portal}bridge/logout?redirectUri=...   -> invalidate the portal SSO session
 *
 * The correlation id is kept in the PHP session between the login redirect
 * and the callback, exactly like the original standalone "sso bridge".
 *
 * ---------------------------------------------------------------------
 */

namespace GlpiPlugin\Ssobridge;

use Html;
use RuntimeException;

final class SsoClient
{
    /**
     * PHP session key holding the correlation id.
     */
    public const SESSION_KEY = 'ssobridge_correlation_id';

    private const HTTP_TIMEOUT = 10;

    /**
     * Start the SSO login: store a correlation id, then redirect the browser
     * to the portal. Never returns on success (redirect is thrown).
     *
     * @param string|null $redirect Optional GLPI relative URL to come back to after login.
     */
    public static function startLogin(?string $redirect = null): void
    {
        $cid = self::getCorrelationId();

        $callback_uri = self::buildCallbackUri();
        if ($redirect !== null && $redirect !== '') {
            $sep = (strpos($callback_uri, '?') === false) ? '?' : '&';
            $callback_uri .= $sep . 'redirect=' . rawurlencode($redirect);
        }

        $sso_url = Config::portalUrl() . 'redirect'
            . '?correlationId=' . rawurlencode($cid)
            . '&redirectUri=' . rawurlencode($callback_uri);

        Html::redirect($sso_url);
    }

    /**
     * Retrieve the validated identity from the SSO portal.
     *
     * @return array{email: string, username: string, error: string}
     */
    public static function retrieveLoginInfo(string $correlationId): array
    {
        $token = Config::accessToken();
        $url   = Config::portalUrl() . 'bridge/check'
            . '?token=' . rawurlencode($token)
            . '&correlationId=' . rawurlencode($correlationId);

        $body = self::httpGet($url);
        if ($body === null) {
            return [
                'email'    => '',
                'username' => '',
                'error'    => sprintf('Cannot reach the SSO portal at "%s".', Config::portalUrl()),
            ];
        }

        $data = json_decode($body, true);
        if (!is_array($data)) {
            return [
                'email'    => '',
                'username' => '',
                'error'    => 'Invalid response received from the SSO portal.',
            ];
        }

        if (isset($data['error'])) {
            return [
                'email'    => '',
                'username' => '',
                'error'    => (string) $data['error'],
            ];
        }

        return [
            'email'    => (string) ($data['email'] ?? ''),
            'username' => (string) ($data['username'] ?? ''),
            'error'    => '',
        ];
    }

    /**
     * URL used to invalidate the SSO session on the portal.
     */
    public static function ssoLogoutUrl(string $redirectUri): string
    {
        return Config::portalUrl() . 'bridge/logout?redirectUri=' . rawurlencode($redirectUri);
    }

    /**
     * Build (and optionally store) a correlation id.
     * Prefers the id generated by the portal, falls back to a local random id.
     */
    private static function getCorrelationId(bool $storeInSession = true): string
    {
        $correlationId = '';

        $url = Config::portalUrl() . 'bridge/cid?token=' . rawurlencode(Config::accessToken());
        $body = self::httpGet($url);
        if ($body !== null) {
            $data = json_decode($body, true);
            if (is_array($data) && isset($data['correlationId']) && $data['correlationId'] !== '') {
                $correlationId = (string) $data['correlationId'];
            }
        }

        if ($correlationId === '') {
            try {
                $correlationId = bin2hex(random_bytes(32));
            } catch (\Exception $e) {
                throw new RuntimeException('Cannot generate a valid correlation id.');
            }
        }

        if ($storeInSession && session_status() === PHP_SESSION_ACTIVE) {
            $_SESSION[self::SESSION_KEY] = $correlationId;
        }

        return $correlationId;
    }

    /**
     * Callback URI used in the SSO redirect.
     * Either the configured SSO_CALLBACK_URI or a value built from the request.
     */
    private static function buildCallbackUri(): string
    {
        $configured = Config::callbackUri();
        if ($configured !== '') {
            return $configured;
        }

        $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
            || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
        $scheme = $https ? 'https' : 'http';
        $host   = $_SERVER['HTTP_HOST'] ?? ($_SERVER['SERVER_NAME'] ?? 'localhost');

        // This script lives in .../plugins/ssobridge/front/, callback.php is a sibling.
        $script_dir = rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/')), '/');

        return $scheme . '://' . $host . $script_dir . '/callback.php';
    }

    /**
     * Lightweight HTTP GET helper (curl first, file_get_contents fallback).
     */
    private static function httpGet(string $url): ?string
    {
        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            if ($ch !== false) {
                curl_setopt_array($ch, [
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_CONNECTTIMEOUT => self::HTTP_TIMEOUT,
                    CURLOPT_TIMEOUT        => self::HTTP_TIMEOUT,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_MAXREDIRS      => 3,
                ]);
                $body  = curl_exec($ch);
                $error = curl_error($ch);
                curl_close($ch);
                return ($body === false) ? null : (string) $body;
            }
        }

        $context = stream_context_create(['http' => ['timeout' => self::HTTP_TIMEOUT]]);
        $body = @file_get_contents($url, false, $context);
        return ($body === false) ? null : $body;
    }
}
